### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by davydog187** [tv-labs/lua#6]
- [x] Full API coverage matching the `Luerl.New` interface
- [x] Livebook guide for working with Lua
- [x] Examples of including preludes into your Lua scripts (see [example on twitter](https://x.com/RicoMoorman/status/1765707094437642490?s=20) and [Github Repo](https://github.com/rmoorman/example-elixir-lua))
- [x] Example of writing a `deflua` function that modifies state
- [x] Loaded files with a syntax error should return a syntax error message

**Comment by Papipo** [comment]
Hey, nice work on this wrapper!

If I want to intercept calls to `require` because my scripts have tenancy  and I can't just read from the filesystem (let's say scripts are stored in the DB), how can I do that? I was able in the past to do it using luerl directly but I am not sure if this library provides a mechanism to do that.

Let me know if I should open a feature request, thanks!
